### ISSUE TITLE
Only works on Linux/Mac due to path limitations.

### ISSUE THREAD

**Issue by ekinnee** [maxchehab/gh-code#13]
**Describe the bug**
Does not accept Windows paths, only "unix" like paths.

**To Reproduce**
Attempt to set code path on a Windows box

**Expected behavior**
Allow setting of path on Windows.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge Chrome
 - Version: 79.0.294.0

**Comment by maxchehab** [comment]
Hey @ekinnee. Thanks for discovering this issue. Before I add support for window paths, could you send an example of a window path on your from your machine?

**Comment by ekinnee** [comment]
Example path: C:\Users\erick\Desktop

Anything I've tried in there errors with "The path must start with '/"."

**Comment by maxchehab** [comment]
@ekinnee Awesome. I just added support for creating a configuration with window file paths. However, I am not sure if deeplinking will be supported. If willing, could you download and test the release I created, locally.

https://github.com/maxchehab/gh-code/releases/tag/0.0.3

**Comment by ekinnee** [comment]
![image](https://user-images.githubusercontent.com/1707617/66396408-519fa680-e99f-11e9-9fe4-16e8093f0c5e.png)

It accepts the Windows type path and opens VS Code but never loads intended code from github as it should.

**Comment by maxchehab** [comment]
Sweet. I'll upload extension on the playstore. Expect an update later today :)
